title: MLSamurai: Deep Learning Course
description: Deep Learning Course
theme: just-the-docs

url: https://mlsamurai.github.io/deep_learning_course

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/mlsamurai/deep_learning_course
